### ISSUE TITLE
Centriod_distances

### ISSUE THREAD

**Issue by mavolio** [mavolio/codyn#48]
we went deep down investigated how much centroid distances change and found basically, that they change a little but keep the same basic relationship with some centroids removed. so overall, we are just going to say that centroid distance is a good metric for community change and we shoudl go back to just calling it multivariate change and drop having calculating bray-curtis as an option.

**Comment by wilcoxkr** [comment]
We were worried that, depending on which plots/data were included, this would give us different distance between centroid values because of the way euclidean distances are calculated. the primary concern is that this might cause different distances to be calculated for different subsets of data, and different conclusions drawn from these different runs. To see whether  this was a problem, we calculated distance between centroids for two datasets with all treatments included (pplots and CDR e001 B) and then again with one treatment removed (the one most different). We then compared the distances and PCoA plots calculated using the full and subset data with the hope that these estimates would line up with each other. Calculating variables using a subset of the data changed the distance and PCoA estimates slightly, yet did not change the overall pattern of the data. Our conclusion from these simulations is that the inclusion or exclusion of some data from a data set does not have a substantial impact on the relative comparisons of estimates of distance between centroids. 
[centroid_distances_19March2018.docx](https://github.com/mavolio/codyn/files/1826688/centroid_distances_19March2018.docx)
